matrix:
  - name: Markdown
    aspell:
      lang: en
      ignore-case: true
    #dictionary:
      wordlists:
        - dicts/OpenNebula.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.context:
          context_visible_first: true
          escapes: \\[\\`~]
          delimiters:
            - open: "(?s)^(?P<open> *`{3,})([a-z+]*)$"
              close: "^(?P=open)$"
            - open: "(?P<open>`+)"
              close: "(?P=open)"
            - open: "{%"
              close: "%}"
            - open: "^(redirect_from:)"
              close: "$"
      - pyspelling.filters.markdown:
          markdown_extensions:
            - pymdownx.superfences
            - markdown.extensions.extra
      - pyspelling.filters.html:
          comments: false
          attributes:
            - title
            - alt
          ignores:
            - ":matches(code, pre)"
            - "code"
            - "pre"
            - "blockquote"
    sources:
      - content/**/*.md
    default_encoding: utf-8
